from tkinter import *
a = Tk()
a.title("Note Pad")
a.geometry("500x500+100+100")
m1 = Menu()
l1 = Menu()
l1.add_command(label="New           ctrl+N")
l1.add_command(label="New Window    ctrl+shift+N")
l1.add_command(label="Open          ctrl+O")
l1.add_command(label="Save          ctrl+S")
l1.add_command(label="Save as       ctrl+shift+S")
l1.add_command(label="Page setup")
l1.add_command(label="Print         ctrl+P")
l1.add_command(label="Exit")
l2 = Menu()
l2.add_command(label="Undo                  ctrl+Z")
l2.add_command(label="Cut                   ctrl+X")
l2.add_command(label="Copy                  ctrl+C")
l2.add_command(label="Paste                 ctrl+V")
l2.add_command(label="Delete                del")
l2.add_command(label="Search with bing...   ctrl+E ")
l2.add_command(label="Find                  ctrl+F")
l2.add_command(label="Find Next             f3")
l2.add_command(label="Find previous         shift+f3")
l2.add_command(label="replace               ctrl+H")
l2.add_command(label="go to...              ctrl+G")
l2.add_command(label="Select all            ctrl+a")
l2.add_command(label="time/date             f5")
l3 = Menu()
l3.add_command(label="word wrap")
l3.add_command(label="font")
l4 = Menu()
l4.add_command(label="zoom")
# l4.add_cascade(label="zoom in")
l4.add_command(label="status bar")
l5 = Menu()
l5.add_command(label="view help")
l5.add_command(label="feedback")
l5.add_command(label="About notepad")
m1.add_cascade(label='file', menu=l1)
m1.add_cascade(label='edit', menu=l2)
m1.add_cascade(label='format', menu=l3)
m1.add_cascade(label='view', menu=l4)
m1.add_cascade(label='help', menu=l5)
a.config(menu=m1)
a.mainloop()